##
# Project Title
#
# @file
# @version 0.1

all: espera_sig n_espera_sig lee_signal envia_signal

espera_sig: espera_sig.c
	gcc -o espera_sig espera_sig.c

n_espera_sig: n_espera_sig.c
	gcc -o n_espera_sig n_espera_sig.c

lee_signal: lee_signal.c
	gcc -o lee_signal lee_signal.c

envia_signal: envia_signal.c
	gcc -o envia_signal envia_signal.c

clean:
	rm -rf lee_signal n_espera_sig espera_sig


# end
